// Экшены для редьюсера общей ленты заказов
export const LOAD_ALL_ORDERS_CONNECT = 'LOAD_ALL_ORDERS_CONNECT';
export const LOAD_ALL_ORDERS_DISCONNECT = 'LOAD_ALL_ORDERS_DISCONNECT';

export const LOAD_ALL_ORDERS_CONNECTING = 'LOAD_ALL_ORDERS_CONNECTING';
export const LOAD_ALL_ORDERS_OPEN = 'LOAD_ALL_ORDERS_OPEN';
export const LOAD_ALL_ORDERS_CLOSE = 'LOAD_ALL_ORDERS_CLOSE';
export const LOAD_ALL_ORDERS_MESSAGE = 'LOAD_ALL_ORDERS_MESSAGE';
export const LOAD_ALL_ORDERS_ERROR = 'LOAD_ALL_ORDERS_ERROR';


// Экшены для редьюсера истории заказов пользователя
export const LOAD_USERS_ORDERS_CONNECT = 'LOAD_USERS_ORDERS_CONNECT';
export const LOAD_USERS_ORDERS_DISCONNECT = 'LOAD_USERS_ORDERS_DISCONNECT';

export const LOAD_USERS_ORDERS_CONNECTING = 'LOAD_USERS_ORDERS_CONNECTING';
export const LOAD_USERS_ORDERS_OPEN = 'LOAD_USERS_ORDERS_OPEN';
export const LOAD_USERS_ORDERS_CLOSE = 'LOAD_USERS_ORDERS_CLOSE';
export const LOAD_USERS_ORDERS_MESSAGE = 'LOAD_USERS_ORDERS_MESSAGE';
export const LOAD_USERS_ORDERS_ERROR = 'LOAD_USERS_ORDERS_ERROR';


// Статусы подключения вебсокета для редьюсера
export const WebsocketStatus = {
  CONNECTING: 'CONNECTING',
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE'
}



